workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play # Add your credentials here
      vars:
        PACKAGE_NAME: "com.pdfcompressor.lite"
      java: 17
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      
      - name: Flutter analyze
        script: | 
          flutter analyze
      
      - name: Build AAB with Flutter
        script: | 
          flutter build appbundle --release
    
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true

  android-apk:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.pdfcompressor.lite"
      java: 17
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      
      - name: Build APK with Flutter
        script: | 
          flutter build apk --release --split-per-abi
    
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true

  android-debug:
    name: Android Debug Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.pdfcompressor.lite"
      java: 17
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      
      - name: Build debug APK
        script: | 
          flutter build apk --debug
    
    artifacts:
      - build/**/outputs/**/*.apk
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
